language: go

go:
  - 1.x

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - cd vendor/github.com/google/brotli
  - ./configure-cmake
  - make && sudo make install
  - cd ../../../..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - go test ./shadow

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tiny .
  - docker images
  - docker tag tiny $DOCKER_USERNAME/tiny
  - docker push $DOCKER_USERNAME/tiny
