language: go

go:
  - 1.x

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tiny .
  - docker images
  - docker tag tiny $DOCKER_USERNAME/tiny
  - docker push $DOCKER_USERNAME/tiny
