language: go

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/tiny .
  - docker tag $DOCKER_USERNAME/tiny $DOCKER_USERNAME/tiny:2.0.0
  - docker push $DOCKER_USERNAME/tiny
  - docker push $DOCKER_USERNAME/tiny:2.0.0
  - docker images