language: go

go:
  - 1.x


script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/tiny .
  - docker push $DOCKER_USERNAME/tiny
  - docker images
